Pages/ApplicationData.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class ApplicationDataModel : PageModel
    {
        private readonly ILogger<ApplicationDataModel> _logger;


        public ApplicationDataModel(ILogger<ApplicationDataModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/ApplicationHistory.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class ApplicationHistoryModel : PageModel
    {
        private readonly ILogger<ApplicationHistoryModel> _logger;

        // 
        public List<Mock.Data.PromotionApplication> Applications { get; set; } = new List<Mock.Data.PromotionApplication> { };


        public ApplicationHistoryModel(ILogger<ApplicationHistoryModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            //
            // Fill with MOCK Data!

            Applications = Mock.Services.EEYWebService.getPromotionApplications();
        }

    }
}

Pages/CheckDetails.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EEY.DigitalServices.API;
using EEY.DigitalServices.Data;
using System;
using Microsoft.AspNetCore.Http;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class CheckDetailsModel : PageModel
    {
        private readonly ILogger<CheckDetailsModel> _logger;
        private PromotionApplicationQualificationService _paqService { get; set; }

        [BindProperty]
        public int QualificationKey { get; set; }

        public Mock.Data.PromotionApplication CurrentApplication { get; set; } = new Mock.Data.PromotionApplication(0, new Mock.Data.PublishedPost(), false);
        public List<PromotionApplicationQualification> TeacherQualifications { get; set; } = new List<PromotionApplicationQualification>();
        public Mock.Data.Teacher ApplicantTeacher { get; set; } = new Mock.Data.Teacher();

        public CheckDetailsModel(ILogger<CheckDetailsModel> logger, PromotionApplicationQualificationService pacService)
        {
            _logger = logger;
            _paqService = pacService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            int ApplicationIndex;

            if (HttpContext.Session.TryGetValue("ApplicationIndex", out byte[] result))
            {
                ApplicationIndex = (int) HttpContext.Session.GetInt32("ApplicationIndex");

                if (ApplicationIndex > 0)
                {
                    ApplicantTeacher = Mock.Services.EEYWebService.getPersonalInfo("876123");

                    CurrentApplication = Mock.Services.EEYWebService.getApplication(ApplicationIndex);

                    // CID - DEBUGGING:
                    int dummyApplicationIndex = 1;

                    TeacherQualifications = await _paqService.GetAppQualifications(dummyApplicationIndex);

                }
                else
                    return NotFound();

            }
            else
                return NotFound();


            return Page();

        }

        public IActionResult OnPostAddEditQualification()
        {
            HttpContext.Session.SetInt32("QualificationKey", QualificationKey);
            return RedirectToPage("/QualificationsAddEdit");
        }

    }

}

Pages/EditEmailDetails.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class EditEmailDetailsModel : PageModel
    {
        private readonly ILogger<EditEmailDetailsModel> _logger;


        [BindProperty, Required]
        public string EMail { get; set; }

        [BindProperty]
        public Mock.Data.Teacher ApplicantTeacher { get; set; }


        public EditEmailDetailsModel(ILogger<EditEmailDetailsModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            int ApplicationIndex;

            if (HttpContext.Session.TryGetValue("ApplicationIndex", out byte[] resultai))
            {
                ApplicationIndex = (int) HttpContext.Session.GetInt32("ApplicationIndex");

                if (ApplicationIndex > 0)
                {
                    // Get the data from EEY Web Service
                    ApplicantTeacher = Mock.Services.EEYWebService.getPersonalInfo("876123");

                    // Polulate bind property
                    EMail = ApplicantTeacher.EMail;

                    return Page();
                }

            }

            return NotFound();

        }

        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {

                // Update record with value from page
                ApplicantTeacher.EMail = EMail;
                
                // Update record using EEY Web Service
                Mock.Services.EEYWebService.updatePersonalInfo(ApplicantTeacher);

                // CID - SHOULD RETURN TO THE REFERENCING PAGE.
                // I.E. IF I AM COMING FROM PAGE CheckDetails, I SHOULD RETURN TO THAT

                return RedirectToPage("/CheckDetails");

            }

        }

    }

}

Pages/EditPhoneDetails.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class EditPhoneDetailsModel : PageModel
    {
        private readonly ILogger<EditPhoneDetailsModel> _logger;

        [BindProperty, Required]
        public string TelNumber { get; set; }

        [BindProperty]
        public Mock.Data.Teacher ApplicantTeacher { get; set; }


        public EditPhoneDetailsModel(ILogger<EditPhoneDetailsModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            int ApplicationIndex;

            if (HttpContext.Session.TryGetValue("ApplicationIndex", out byte[] resultai))
            {
                ApplicationIndex = (int) HttpContext.Session.GetInt32("ApplicationIndex");

                if (ApplicationIndex > 0)
                {
                    // Get the data from EEY Web Service
                    ApplicantTeacher = Mock.Services.EEYWebService.getPersonalInfo("876123");

                    // Polulate bind property
                    TelNumber = ApplicantTeacher.TelNumber;

                    return Page();

                }

            }

            return NotFound();

        }

        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {

                // Update record with value from page
                ApplicantTeacher.TelNumber = TelNumber;

                // Update record using EEY Web Service
                Mock.Services.EEYWebService.updatePersonalInfo(ApplicantTeacher);

                // CID - SHOULD RETURN TO THE REFERENCING PAGE.
                // I.E. IF I AM COMING FROM PAGE CheckDetails, I SHOULD RETURN TO THAT

                return RedirectToPage("/CheckDetails");

            }

        }

    }

}

Pages/Error.cshtml.cs
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace EEY.DigitalServices.Promotions.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/MilitaryCert.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class MilitaryCertModel : PageModel
    {
        private readonly ILogger<MilitaryCertModel> _logger;

        public MilitaryCertModel(ILogger<MilitaryCertModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/PositionSelection.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class PositionSelectionModel : PageModel
    {
        private readonly ILogger<PositionSelectionModel> _logger;

        [BindProperty]
        public int ApplicationIndex { get; set; }

        //
        public List<Mock.Data.PublishedPost> AvailablePosts { get; set; } = new List<Mock.Data.PublishedPost> { };

        // 
        public List<Mock.Data.PromotionApplication> Applications { get; set; } = new List<Mock.Data.PromotionApplication> { };

        public PositionSelectionModel(ILogger<PositionSelectionModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            //
            // CID - Fill with MOCK Data!

            AvailablePosts = Mock.Services.EEYWebService.getAvailablePosts();

            Applications = Mock.Services.EEYWebService.getPromotionApplications();

            HttpContext.Session.SetInt32("ApplicationIndex", ApplicationIndex);

            return Page();
        }

        public IActionResult OnPostEditApplication()
        {
            HttpContext.Session.SetInt32("ApplicationIndex", ApplicationIndex);
            return RedirectToPage("/CheckDetails");
        }

        public IActionResult OnPostNewApplication()
        {
            HttpContext.Session.SetInt32("ApplicationIndex", ApplicationIndex);
            return RedirectToPage("/Qualifications");
        }

    }
}

Pages/Qualifications.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EEY.DigitalServices.Data;
using EEY.DigitalServices.API;
using System;
using Microsoft.AspNetCore.Http;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class QualificationsModel : PageModel
    {
        private readonly ILogger<QualificationsModel> _logger;
        private PromotionApplicationQualificationService _paqService { get; set; }

        [BindProperty]
        public int QualificationKey { get; set; }

        public List<PromotionApplicationQualification> TeacherQualifications { get; set; } = new List<PromotionApplicationQualification>();

        public QualificationsModel(ILogger<QualificationsModel> logger, PromotionApplicationQualificationService pacService)
        {
            _logger = logger;
            _paqService = pacService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            int ApplicationIndex;

            if (HttpContext.Session.TryGetValue("ApplicationIndex", out byte[] result))
            {
                ApplicationIndex = (int) HttpContext.Session.GetInt32("ApplicationIndex");

                if (ApplicationIndex > 0)
                {
                    // CID - DEBUGGING:
                    int dummyApplicationIndex = 1;

                    TeacherQualifications = await _paqService.GetAppQualifications(dummyApplicationIndex);
                }
                else
                    return NotFound();
            }
            else
                return NotFound();


            return Page();

        }

        public IActionResult OnPostAddEditQualification()
        {
            HttpContext.Session.SetInt32("QualificationKey", QualificationKey);
            return RedirectToPage("/QualificationsAddEdit");
        }

        public IActionResult OnPostNextPage()
        {
            return RedirectToPage("/CheckDetails");
        }
    }
}

Pages/QualificationsAddEdit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EEY.DigitalServices.Data;
using EEY.DigitalServices.API;
using System;
using Microsoft.AspNetCore.Http;

namespace EEY.DigitalServices.Promotions.Pages
{
    public class QualificationsAddEditModel : PageModel
    {
        private readonly ILogger<QualificationsAddEditModel> _logger;
        private PromotionApplicationQualificationService _paqService { get; set; }

        [BindProperty]
        public PromotionApplicationQualification Qualification { get; set; } = new PromotionApplicationQualification();


        public QualificationsAddEditModel(ILogger<QualificationsAddEditModel> logger, PromotionApplicationQualificationService pacService)
        {
            _logger = logger;
            _paqService = pacService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            int ApplicationIndex, QualificationKey;

            if (HttpContext.Session.TryGetValue("ApplicationIndex", out byte[] resultai))
            {
                ApplicationIndex = (int) HttpContext.Session.GetInt32("ApplicationIndex");

                if (HttpContext.Session.TryGetValue("QualificationKey", out byte[] resultqk))
                {
                    QualificationKey = (int) HttpContext.Session.GetInt32("QualificationKey");

                    if (ApplicationIndex > 0 && QualificationKey >= 0)
                    {
                        if (QualificationKey > 0)
                        {
                            Qualification = await _paqService.Get(QualificationKey);

                            // CID - DEBUGGING:
                            // The service does not return a valid code (always 1).
                            // Replace it with the one from page
                            Qualification.ApplicationCode = ApplicationIndex;
                        }
                        else
                        {
                            Qualification = new PromotionApplicationQualification();
                            Qualification.ApplicationCode = ApplicationIndex;
                        }

                    }
                    else
                        return NotFound();

                }
                else
                    return NotFound();

            }
            else
                return NotFound();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if (!ModelState.IsValid || Qualification == null)
            {
                return Page();
            }
            else
            {
                if (Qualification != null)
                {
                    // CID - DEBUGGING - SHOULD BE ADDRESSED
                    if (Qualification.FromYear == 0)
                        Qualification.FromYear = 1971;

                    // CID - DEBUGGING:
                    int originalApplicationIndex = Qualification.ApplicationCode;
                    Qualification.ApplicationCode = 1;
                    
                    Qualification = await _paqService.Save(Qualification);

                    // CID - DEBUGGING:
                    Qualification.ApplicationCode = originalApplicationIndex;

                    // CID - SHOULD RETURN TO THE REFERENCING PAGE.
                    // I.E. IF I AM COMING FROM PAGE CheckDetails, I SHOULD RETURN TO THAT
                    return RedirectToPage("/Qualifications");
                }

            }

            return NotFound();

        }

    }
}

Pages/ApplicationData.cshtml
@page

@model EEY.DigitalServices.Promotions.Pages.ApplicationDataModel

@{
    ViewData["Title"] = "Στοιχεία Αίτησης";
}

<!--Main-->
<main class="govcy-container govcy-my-2" id="mainContainer">
    <div class="row">
        <div class="govcy-col-9 govcy-order-last">

            <h1>@ViewData["Title"]</h1>

        </div>

    </div>
</main>

Pages/CheckDetails.cshtml
@page

@using Newtonsoft.Json
@using EEY.DigitalServices.Data

@model EEY.DigitalServices.Promotions.Pages.CheckDetailsModel
@{
    ViewData["Title"] = "Ελέγξτε αν τα στοιχεία της αίτησης σας είναι σωστά";
}

<!--Main-->
<main class="govcy-container govcy-my-2" id="mainContainer">
    <div class="row">
        <div class="govcy-col-9 govcy-order-last">

            <h1>@ViewData["Title"]</h1>

            @{
                int i = 1;
            }

            <div class="govcy-table-responsive">
                <table class="govcy-table">

                    <tr>
                        <td><b>Προσωπικά Στοιχεία</b></td>
                        <td></td>
                        <td>
                            <b>Ονοματεπώνυμο: </b>
                            <br>
                            <span id=fullNameCheck>@Model.ApplicantTeacher.FirstName @Model.ApplicantTeacher.LastName</span>
                            <br>
                            <b>Αρ. Φακέλου: </b>
                            <br>
                            <span id=fileNumberCheck>@Model.ApplicantTeacher.FileNumber</span>
                        </td>
                        <td></td>
                    </tr>

                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <b>Τηλέφωνο: </b>
                            <br>
                            <span id=telNumberCheck>@Model.ApplicantTeacher.TelNumber</span>
                        </td>
                        <td>
                            <br>
                            <div class="govcy-mb-4"><a href="/EditPhoneDetails">Αλλαγή</a></div>
                        </td>
                    </tr>

                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <b>E-mail: </b>
                            <br>
                            <span id=eMailCheck>@Model.ApplicantTeacher.EMail</span>
                        </td>
                        <td>
                            <br>
                            <div class="govcy-mb-4"><a href="/EditEmailDetails">Αλλαγή</a></div>
                        </td>
                    </tr>

                    <tr>
                        <td><b>Θέση για την οποία υποβάλλεται η αίτηση</b></td>
                        <td></td>
                        <td><span id=positionCheck>@Model.CurrentApplication.PostDetails.Description</span></td>
                        <td></td>
                    </tr>

                    @foreach (PromotionApplicationQualification qualification in Model.TeacherQualifications)
                    {
                        string titleTagID = "title" + i;
                        string institutiionTagID = "institution" + i;
                        string countryTagID = "country" + i;
                        string yearToTagID = "yearTo" + i;
                        string actionTagID = "action" + i;
                        string qualificationsHeading;

                        if (@i == 1)
                            qualificationsHeading = "Πρόσθετα Ακαδημαϊκά Προσόντα";
                        else
                            qualificationsHeading = "";
                        <tr>
                            <td><b>@qualificationsHeading</b></td>
                            <td><b>@i.</b></td>
                            <td>
                                <b>Τίτλος Σπουδών: </b><span id=@titleTagID>@qualification.Title</span>
                                <br>
                                <b>Ίδρυμα: </b><span id=@institutiionTagID>@qualification.Institution</span>
                                <br>
                                <b>Χώρα: </b><span id=@countryTagID>@qualification.Country</span>
                                <br>
                                <b>Έτος απόκτησης: </b><span id=@yearToTagID>@qualification.ToYear</span>
                            </td>
                            <td>
                                <form id=@actionTagID method="post" class="govcy-form" asp-page-handler="AddEditQualification">
                                    @{
                                        Model.QualificationKey = qualification.AutoKey;
                                    }
                                    <input type="hidden" asp-for="@Model.QualificationKey" />
                                    <div class="govcy-mb-4">
                                        <a href="#" onclick=document.getElementById("@actionTagID").submit();>Αλλαγή</a>
                                    </div>
                                </form>
                            </td>
                        </tr>

                        i++;
                    }

                    <tr>
                        <td><b>Πιστοποιητικό στρατολογικής κατάστασης "Α"</b></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>

                </table>
            </div>

        </div>

    </div>
</main>

Pages/MilitaryCert.cshtml
@page

@model EEY.DigitalServices.Promotions.Pages.MilitaryCertModel

@{
    ViewData["Title"] = "Επισυνάψτε το πιστοποιητικό στρατολογικής κατάστασης \"Α\"";
}

<!--Main-->
<main class="govcy-container govcy-my-2" id="mainContainer">
    <div class="row">
        <div class="govcy-col-9 govcy-order-last">

            <h1>@ViewData["Title"]</h1>

        </div>

    </div>
</main>

Pages/PositionSelection.cshtml
@page

@using Newtonsoft.Json
@using EEY.DigitalServices.Promotions.Mock.Data

@model EEY.DigitalServices.Promotions.Pages.PositionSelectionModel

@{
    ViewData["Title"] = "Μπορείτε να υποβάλετε αίτηση για τις πιο κάτω θέσεις";
}

<!--Main-->
<main class="govcy-container govcy-my-2" id="mainContainer">
    <div class="row">
        <div class="govcy-col-9 govcy-order-last">

            <h1>@ViewData["Title"]</h1>

            @{
                int i = 1;
            }

            <div class="govcy-table-responsive">
                <table class="govcy-table">
                    @foreach (PromotionApplication application in Model.Applications)
                    {
                        string positionTagID = "position" + i;
                        string publicationTagID = "publication" + i;
                        string deadlineTagID = "deadline" + i;
                        string actionTagID = "action" + i;

                        if (application.Active)
                        {
                            <tr>
                                <td><b>@i</b></td>
                                <td>
                                    <b>Θέση: </b><span id=@positionTagID>@application.PostDetails.Description</span><br>
                                    <b>Προκήρυξη: </b><span id=@publicationTagID>@application.PostDetails.PublicationID</span><br>
                                    <b>Προθεσμία Υποβολής Αίτησης: </b><span id=@deadlineTagID>@application.PostDetails.OpensOn</span>
                                </td>
                                <td>
                                    <b>Παραλήφθηκε</b>
                                </td>
                                <td>
                                    <form id=@actionTagID method="post" class="govcy-form" asp-page-handler="EditApplication">
                                        @{
                                            Model.ApplicationIndex = application.IDNumber;
                                        }
                                        <input type="hidden" asp-for="@Model.ApplicationIndex" />
                                        <div class="govcy-mb-4">
                                            <a href="#" onclick=document.getElementById("@actionTagID").submit();>Επεξεργασία</a>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    @foreach (PublishedPost availablePost in Model.AvailablePosts)
                    {
                        string positionTagID = "position" + i;
                        string publicationTagID = "publication" + i;
                        string deadlineTagID = "deadline" + i;
                        string actionTagID = "action" + i;

                        <tr>
                            <td><b>@i</b></td>
                            <td>
                                <b>Θέση: </b><span id=@positionTagID>@availablePost.Description</span><br>
                                <b>Προκήρυξη: </b><span id=@publicationTagID>@availablePost.PublicationID</span><br>
                                <b>Προθεσμία Υποβολής Αίτησης: </b><span id=@deadlineTagID>@availablePost.OpensOn</span>
                            </td>
                            <td>
                            </td>
                            <td>
                                <form id=@actionTagID method="post" class="govcy-form" asp-page-handler="NewApplication">
                                    @{
                                        Model.ApplicationIndex = availablePost.IDNumber;
                                    }
                                    <input type="hidden" asp-for="@Model.ApplicationIndex" />
                                    <div class="govcy-mb-4">
                                        <a href="#" onclick=document.getElementById("@actionTagID").submit();>Αίτηση</a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        i++;
                    }
                </table>
            </div>

            <div class="govcy-mb-4"><a href="/ApplicationHistory">Ιστορικό Ολοκληρωμένων Αιτήσεων</a></div>

        </div>

    </div>
</main>

Pages/Qualifications.cshtml
@page

@using Newtonsoft.Json
@using EEY.DigitalServices.Data

@model EEY.DigitalServices.Promotions.Pages.QualificationsModel

@{
    ViewData["Title"] = "Ενημερώστε τα ακαδημαϊκά σας προσόντα";
}

<!--Main-->
<main class="govcy-container govcy-my-2" id="mainContainer">
    <div class="row">
        <div class="govcy-col-9 govcy-order-last">

            <h1>@ViewData["Title"]</h1>

            <p>Μπορείτε να προσθέσετε νέα ακαδημαϊκά προσόντα.  Μπορείτε να διορθώσετε τα προσόντα που έχετε δηλώσει σε προηγούμενη αίτηση σας.</p>

            @{
                int i = 1;
            }

            <div class="govcy-table-responsive">
                <table class="govcy-table">
                    @foreach (PromotionApplicationQualification qualification in Model.TeacherQualifications)
                    {
                        string titleTagID = "title" + i;
                        string institutiionTagID = "institution" + i;
                        string countryTagID = "country" + i;
                        string yearToTagID = "yearTo" + i;
                        string actionTagID = "action" + i;

                        <tr>
                            <td><b>@i</b></td>
                            <td>
                                <b>Τίτλος Σπουδών:</b>
                                <br>
                                <b>Ίδρυμα:</b>
                                <br>
                                <b>Χώρα:</b>
                                <br>
                                <b>Έτος απόκτησης:</b>
                            </td>
                            <td>
                                <span id=@titleTagID>@qualification.Title</span>
                                <br>
                                <span id=@institutiionTagID>@qualification.Institution</span>
                                <br>
                                <span id=@countryTagID>@qualification.Country</span>
                                <br>
                                <span id=@yearToTagID>@qualification.ToYear</span>
                            </td>
                            <td>
                                <form id=@actionTagID method="post" class="govcy-form" asp-page-handler="AddEditQualification">
                                    @{
                                        Model.QualificationKey = qualification.AutoKey;
                                    }
                                    <input type="hidden" asp-for="@Model.QualificationKey" />
                                    <div class="govcy-mb-4">
                                        <a href="#" onclick=document.getElementById("@actionTagID").submit();>Αλλαγή</a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        i++;
                    }
                </table>
            </div>

            <form method="post" class="govcy-form" asp-page-handler="AddEditQualification">
                @{
                    Model.QualificationKey = 0;
                }
                <input type="hidden" asp-for="@Model.QualificationKey" />
                <div>
                    <input type="submit" value="Προσθήκη Νέου" class="btn govcy-btn-secondary" />
                </div>
            </form>

            <br>

            <form method="post" class="govcy-form" asp-page-handler="NextPage">
                <div>
                    <input type="submit" value="Επόμενο" class="btn govcy-btn-primary" />
                </div>
            </form>

        </div>

    </div>
</main>